### ISSUE TITLE
null data column causes messaging npe on samsung 4.4.2 note3  and 4.2 on s4

### ISSUE THREAD

**Issue by sbaar** [commonsguy/cwac-provider#20]
using the legacy cursor wrapper on the s4 on 4.2 or note 3 with 4.4.2 will cause an npe on samsung's messaging app only when trying to share an mp4 (on images it's fine). Not using the legacy cursor wrapper will cause it to just fail and toast that the file type is not supported, but not including the legacy cursor wrapper will cause problems on other devices.

To fix this problem, I just return the uri for the data column instead of null and it seems to work in all apps and on the problematic samsung device and my nexus 6 7.0.

Is there a reason the data column is null? If not, I recommend changing it for better compatibility.

btw, here is the stacktrace for the note 3 4.4.2 messaging crash. Note these line numbers do not correspond to anything you will find on grepcode for aosp for ~4.4.2, meaning this code was almost certainly changed by samsung and the ultimate cause will likely remain an enigma.
`10-27 20:23:55.475 18928-18948/? E/AndroidRuntime: FATAL EXCEPTION: addAttachment
                                                   Process: com.android.mms, PID: 18928
                                                   java.lang.NullPointerException
                                                       at com.android.mms.model.VideoModel.initFromContentUri(VideoModel.java:131)
                                                       at com.android.mms.model.VideoModel.initModelFromUri(VideoModel.java:73)
                                                       at com.android.mms.model.VideoModel.<init>(VideoModel.java:54)
                                                       at com.android.mms.data.WorkingMessage.appendMedia(WorkingMessage.java:3881)
                                                       at com.android.mms.data.WorkingMessage.setAttachment(WorkingMessage.java:851)
                                                       at com.android.mms.util.HandleComposerAttachment.addVideo(HandleComposerAttachment.java:1199)
                                                       at com.android.mms.util.HandleComposerAttachment.addMedia(HandleComposerAttachment.java:1089)
                                                       at com.android.mms.util.HandleComposerAttachment.addMedia(HandleComposerAttachment.java:1506)
                                                       at com.android.mms.util.HandleComposerAttachment$42.run(HandleComposerAttachment.java:2881)
                                                       at java.lang.Thread.run(Thread.java:841)
`

**Comment by commonsguy** [comment]
> I just return the uri for the data column instead of null

What `Uri`? Do you mean the `Uri` that was used to query the provider?

> Is there a reason the data column is null?

Well, when dealing with arbitrary compatibility issues, there's no specific value that can make all those issues go away. I tried `null`; it seemed to help.

> If not, I recommend changing it for better compatibility.

I can certainly look to make it a configuration option.

**Comment by commonsguy** [comment]
Addressed in v0.5.0.
