### ISSUE TITLE
AssetStrategy does not work with action_send intent handled by Gmail

### ISSUE THREAD

**Issue by hmcfletch** [commonsguy/cwac-provider#6]
On my Nexus 5 running KitKat 4.4.2.

The issues revolves around Gmail expecting a size, but the size returned is -1. Gmail seems to be treating it as an unsigned int/long, so I get the error that it can't attach files of 25MB. Adding the following to AssetStrategy seemed to get around that problem:

```
	@Override
	public long getLength(Uri uri) {
		AssetFileDescriptor afd;
		try {
			afd = appContext.getAssets().openFd(getFilename(uri));
		} catch (IOException e) {
			Logger.ex(e);
			return super.getLength(uri);
		}

		long size = afd.getLength();

		try {
			afd.close();
		} catch (IOException e) {
			Logger.ex(e);
		}

		if (size == 0) {
			return super.getLength(uri);
		} else {
			return size;
		}
	}

	// extracted for use elsewhere
	private String getFilename(Uri uri) {
		boolean isFirst=true;
		StringBuilder fullPathBuilder=new StringBuilder();

		if (path != null) {
		  fullPathBuilder.append(path);
		}

		List<String> segments=new ArrayList<String>(uri.getPathSegments());

		segments.remove(0); // get rid of first segment

		for (String segment : segments) {
		  if (isFirst) {
			isFirst=false;
			fullPathBuilder.append(segment);
		  }
		  else if (!"..".equals(segment)) {
			fullPathBuilder.append('/');
			fullPathBuilder.append(segment);
		  }
		}

		return fullPathBuilder.toString();
	}
```

Now I am seeing the following error over a dozen times as soon as I select Gmail from the list:

```
10-22 16:17:52.329  30392-31461/com.tophatter E/TransferOutThread﹕ Exception transferring file
    java.io.IOException: write failed: EPIPE (Broken pipe)
            at libcore.io.IoBridge.write(IoBridge.java:455)
            at java.io.FileOutputStream.write(FileOutputStream.java:187)
            at com.commonsware.cwac.provider.AbstractPipeStrategy$TransferOutThread.run(AbstractPipeStrategy.java:131)
     Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
            at libcore.io.Posix.writeBytes(Native Method)
            at libcore.io.Posix.write(Posix.java:202)
            at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
            at libcore.io.IoBridge.write(IoBridge.java:450)
            at java.io.FileOutputStream.write(FileOutputStream.java:187)
            at com.commonsware.cwac.provider.AbstractPipeStrategy$TransferOutThread.run(AbstractPipeStrategy.java:131)
```

Do you have any thoughts on the matter?

**Comment by commonsguy** [comment]
`getLength()` support was added for raw resources and assets in v0.2.3.
