### ISSUE TITLE
java.io.IOException: write failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by jjoseba** [commonsguy/cwac-provider#8]
I get the following error trying to share a file from the assets folder:

	E/TransferOutThread: Exception transferring file
	E/TransferOutThread: java.io.IOException: write failed: EPIPE (Broken pipe)
	E/TransferOutThread:     at libcore.io.IoBridge.write(IoBridge.java:542)
	E/TransferOutThread:     at java.io.FileOutputStream.write(FileOutputStream.java:186)
	E/TransferOutThread:     at com.commonsware.cwac.provider.AbstractPipeStrategy$TransferOutThread.run(AbstractPipeStrategy.java:96)
	E/TransferOutThread:  Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	E/TransferOutThread:     at libcore.io.Posix.writeBytes(Native Method)
	E/TransferOutThread:     at libcore.io.Posix.write(Posix.java:258)
	E/TransferOutThread:     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
	E/TransferOutThread:     at libcore.io.IoBridge.write(IoBridge.java:537)
	E/TransferOutThread:     at java.io.FileOutputStream.write(FileOutputStream.java:186) 
	E/TransferOutThread:     at com.commonsware.cwac.provider.AbstractPipeStrategy$TransferOutThread.run(AbstractPipeStrategy.java:96) 

The file exists, I've tried sending a non-existent file and the error was a FileNotFoundException.
I think I'm creating the Intent and everything correctly, but I paste it here anyway:

	Intent share = new Intent(Intent.ACTION_SEND);
    share.setType("audio/*");
    share.putExtra(Intent.EXTRA_STREAM, PROVIDER.buildUpon().appendPath(soundName + ".mp3").build());
    share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
    startActivity(Intent.createChooser(share, "Share audio"));

I'm using the last version of `cwac-provider`, with Android sdkVersion 23

**Comment by commonsguy** [comment]
If you think that this is a bug in the library, then I need the complete source code to a project that can demonstrate the problem, plus the steps on how to reproduce the problem.

**Comment by jjoseba** [comment]
I've isolated the problem to the simplest code. It's just an Activity that launches the sharing intent in its onStart() method. I've uploaded the complete project here: https://drive.google.com/file/d/0ByCtNqXoOZUEaTNDU3M0V3JRMmc/view?usp=sharing

**Comment by commonsguy** [comment]
OK, and what are you sharing it with? What particular client app (or apps), when you choose it as the `ACTION_SEND` implementation, is triggering the exception?

**Comment by jjoseba** [comment]
Telegram official app. The most recent version (3.2.6).

**Comment by commonsguy** [comment]
I'm not a Telegram user, and your sample project is not getting along with my Android Studio for some reason (perpetual "Sync Now" yellow banner). But, I am able to reproduce the crash with Evernote.

Evernote *does* eventually get the file, though, as I was then able to download it from Evernote and get the MP3 file back (though the filename got mangled to `Audio clip.null`).

I'll work on this some this week and see if I can improve compatibility here.

**Comment by jjoseba** [comment]
Thanks! Maybe you couldn't compile it because of different buidTools version? Or Android Studio? I'm using 21.1.2, and Android Studio 1.4.1. Anyway, if you manage to reproduce it with another app, great! I can test if for you in Telegram after you can have it a look!

PS: I've tried it now, and with whatsapp it seems to work fine :confused: Sorry for not doing it prior to opening the issue, it would have helped narrowing the problem.

**Comment by commonsguy** [comment]
Oh, I was able to build it. I just can't get rid of the "Sync Now" yellow banner that you get when you modify a Gradle build file. Syncing the project files just causes the banner to reappear. It should not be a huge problem. My demo project only handles `ACTION_VIEW`, and I have been meaning to add `ACTION_SEND` as an option for it. So, I'll do that, and see if I can reproduce the problem with the revised demo app.

In the meantime, one thing that you might try is [playing with `aaptOptions`](http://stackoverflow.com/questions/28934333/how-can-i-use-android-aaptoptions) and try to avoid compression on the MP3 file. That *should* be a file extension that's already being skipped, but you never know. I do know that compressed assets tend to be less compatible than are uncompressed assets.

**Comment by commonsguy** [comment]
I believe the problem is file size. I think there's an issue with larger than 64KB files. I may be able to address this in the library.

**Comment by jjoseba** [comment]
I don't get the error anymore (great!), but I still get the `Attatchment not supported` error in Telegram when trying to share a sound (doh!). I've tried adding the `aaptOptions`, with mp3 and ogg files, and whith varying sizes from 15KB to 200KB.
I'll see if I can get some output in the logs from the Telegram app to know what's happening... and I'll also try if changing the files location from the **assets** folder to the **raw** resources folder changes anything.

Anyway, the issue is solved!
PS: One last minor thing. In the docs, you forgot to change the lib version in the `build.gradle` section ;)

Cheers!

**Comment by commonsguy** [comment]
With regards to Telegram, as I don't use it, I don't have a great way of testing it specifically. You might try a test with a `file:///` with the same content; it's possible that Telegram is fine with the `Uri` but just doesn't like the content for some reason. If you come up with fresh evidence, or a way for me to test this that doesn't involve me signing up for Telegram, file a fresh issue.

With respect to the docs, I just pushed a fix -- thanks for pointing that out!
